anchor to safeArea (#1438)
* anchor to safeArea

* fix ci

* improve ci

* fix ci

* try it now

* fix run destination

* remove optional part from ci

* fix

---------

Co-authored-by: Andrii Momot <andrii.momot@m10s.io>

diff --git a/.github/workflows/iOS.yml b/.github/workflows/iOS.yml
--- a/.github/workflows/iOS.yml
+++ b/.github/workflows/iOS.yml
@@ -12,20 +12,37 @@ jobs:
     runs-on: macos-15
     env:
       scheme: ${{ 'Demo' }}
-      destination: ${{ 'platform=iOS Simulator,OS=18.4,name=iPhone 16 Pro' }}
+      destination: ${{ 'platform=iOS Simulator,OS=18.5,name=iPhone 16 Pro' }}
 
     steps:
       - uses: actions/checkout@v4
-      - name: Select Xcode 16.3
-        run: sudo xcode-select -s /Applications/Xcode_16.3.app
+      
+      - name: Select Xcode 16.4
+        shell: bash
+        run: |
+          sudo xcode-select -s /Applications/Xcode_16.4.app
+          XCODE_PATH="$(xcode-select -p)"
+          echo "Using Xcode at ${XCODE_PATH}"
+          xcodebuild -version
+
+        
+      - name: Accept Xcode license & runFirstLaunch
+        run: |
+          # tolerate failures so the job continues if already accepted
+          sudo xcodebuild -license accept || true
+          sudo xcodebuild -runFirstLaunch || true
+        
       - name: Install SwiftLint
         run: brew install swiftlint
+        
       - name: Lint
         run: |
           swiftlint lint
+          
       - name: Build
         run: |
           xcodebuild build-for-testing -scheme "$scheme" -workspace FinniversKit.xcworkspace -destination "$destination"
-      - name: Test        
+          
+      - name: Test
         run: |
           xcodebuild test-without-building -scheme "$scheme" -workspace FinniversKit.xcworkspace -destination "$destination" 
